version: '3.9'

services:
    www:
        build: .
        ports: 
            - "8099:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
    db:
        image: mysql
        ports: 
            - "3377:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: staff
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_INITDB_CHARSET: utf8mb4_unicode_ci
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        command:  mysqld --sql_mode='' --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8899:80
        volumes:
            - ./:/var/www/pma
volumes:
    persistent:
